using System.Diagnostics;
using System.Text;
using System.Text.RegularExpressions;

const string SnippetsFileName = "Snippets.generated.cs";

var stopwatch = Stopwatch.StartNew();
var docsDir = Directory.GetCurrentDirectory();
var componentsPath = Path.Combine(docsDir, "Pages", "Components");
var outputPath = Path.Combine(docsDir, "Models", SnippetsFileName);

if (!Directory.Exists(componentsPath))
{
    Console.WriteLine($"Components path not found: {componentsPath}");
    return 1;
}

// Early exit: if Snippets.generated.cs exists and is newer than all example files, skip generation
var exampleFiles = Directory.EnumerateFiles(componentsPath, "*Example.razor", SearchOption.AllDirectories)
    .OrderBy(f => f.Replace("\\", "/"), StringComparer.Ordinal)
    .ToList();

if (exampleFiles.Count == 0)
{
    var minimalContent = """
        //-----------------------------------------------------------------------
        // AUTO-GENERATED - Do not edit manually
        // This file is autogenerated by ShadcnBlazor.Docs.Compiler
        // <auto-generated />
        //-----------------------------------------------------------------------

        namespace ShadcnBlazor.Docs.Models
        {
            [System.CodeDom.Compiler.GeneratedCodeAttribute("ShadcnBlazor.Docs.Compiler", "0.0.0.0")]
            public static partial class Snippets
            {
            }
        }
        """;
    Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
    File.WriteAllText(outputPath, minimalContent);
    Console.WriteLine("No example files found. Created empty Snippets.generated.cs.");
    return 0;
}

if (File.Exists(outputPath))
{
    var snippetsLastWrite = File.GetLastWriteTimeUtc(outputPath);
    var newestExampleTime = exampleFiles
        .Select(f => File.GetLastWriteTimeUtc(f))
        .Max();

    if (snippetsLastWrite > newestExampleTime)
    {
        Console.WriteLine("Snippets.generated.cs is up-to-date, skipping generation.");
        return 0;
    }
}

var currentCode = File.Exists(outputPath) ? File.ReadAllText(outputPath) : string.Empty;

var sb = new StringBuilder();
sb.AppendLine("//-----------------------------------------------------------------------");
sb.AppendLine("// AUTO-GENERATED - Do not edit manually");
sb.AppendLine("// This file is autogenerated by ShadcnBlazor.Docs.Compiler");
sb.AppendLine("// Any changes will be overwritten on build");
sb.AppendLine("// <auto-generated />");
sb.AppendLine("//-----------------------------------------------------------------------");
sb.AppendLine();
sb.AppendLine("namespace ShadcnBlazor.Docs.Models");
sb.AppendLine("{");
sb.AppendLine("    [System.CodeDom.Compiler.GeneratedCodeAttribute(\"ShadcnBlazor.Docs.Compiler\", \"0.0.0.0\")]");
sb.AppendLine("    public static partial class Snippets");
sb.AppendLine("    {");

foreach (var filePath in exampleFiles)
{
    var fileName = Path.GetFileNameWithoutExtension(filePath);
    var source = File.ReadAllText(filePath, Encoding.UTF8);
    // Strip @namespace, @page, @layout directives
    source = Regex.Replace(source, @"@(namespace|page|layout)\s+.+?\n", string.Empty);
    var escaped = source.Replace("\"", "\"\"").Trim();
    sb.AppendLine($"        public const string {fileName} = @\"{escaped}\";");
    sb.AppendLine();
}

sb.AppendLine("    }");
sb.AppendLine("}");

var newCode = sb.ToString();

if (currentCode != newCode)
{
    Directory.CreateDirectory(Path.GetDirectoryName(outputPath)!);
    File.WriteAllText(outputPath, newCode);
    Console.WriteLine($"Generated snippets for {exampleFiles.Count} examples.");
}
else
{
    File.SetLastWriteTimeUtc(outputPath, DateTime.UtcNow);
    Console.WriteLine("Snippets.generated.cs content unchanged, touched timestamp.");
}

Console.WriteLine($"Docs.Compiler completed in {stopwatch.ElapsedMilliseconds} ms.");
return 0;
