//-----------------------------------------------------------------------
// AUTO-GENERATED - Do not edit manually
// This file is autogenerated by ShadcnBlazor.Docs.Compiler
// Any changes will be overwritten on build
// <auto-generated />
//-----------------------------------------------------------------------

namespace ShadcnBlazor.Docs.Models
{
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ShadcnBlazor.Docs.Compiler", "0.0.0.0")]
    public static partial class Snippets
    {
        public const string ButtonBasicExample = @"<Button>Click Me</Button>";

        public const string ButtonDisabledExample = @"<div class=""flex flex-wrap gap-4"">
    <Button Disabled=""true"">Disabled</Button>
    <Button Variant=""@Variant.Outline"" Disabled=""true"">Disabled Outline</Button>
</div>";

        public const string ButtonIconExample = @"@using EasyAppDev.Blazor.Icons.Lucide

<div class=""flex flex-wrap gap-4"">
    <Button><LuDownload class=""h-4 w-4"" />Download</Button>
    <Button Variant=""@Variant.Outline""><LuMail class=""h-4 w-4"" />Email</Button>
</div>";

        public const string ButtonSizeExample = @"<div class=""flex flex-wrap items-center gap-4"">
    <Button Size=""@Size.Sm"">Small</Button>
    <Button Size=""@Size.Md"">Medium</Button>
    <Button Size=""@Size.Lg"">Large</Button>
</div>";

        public const string ButtonVariantExample = @"<div class=""flex flex-wrap gap-4"">
    <Button>Default</Button>
    <Button Variant=""@Variant.Destructive"">Destructive</Button>
    <Button Variant=""@Variant.Outline"">Outline</Button>
    <Button Variant=""@Variant.Secondary"">Secondary</Button>
    <Button Variant=""@Variant.Ghost"">Ghost</Button>
    <Button Variant=""@Variant.Link"">Link</Button>
</div>";

        public const string PopoverBasicExample = @"@using ShadcnBlazor.Components.Popover.Models

<Popover Open=""@_open""
         AnchorOrigin=""PopoverPlacement.BottomLeft""
         TransformOrigin=""PopoverPlacement.TopLeft""
         WidthMode=""PopoverWidthMode.Adaptive""
         ClampList=""true"">
    <Anchor>
        <Button OnClick=""TogglePopover"">@(_open ? ""Close"" : ""Open"") Popover</Button>
    </Anchor>
    <ChildContent>
        <div class=""w-64 rounded-lg border bg-popover text-popover-foreground shadow-lg"">
            <div class=""px-4 py-3 border-b text-sm font-semibold"">Popover Content</div>
            <ul class=""flex flex-col gap-1 px-3 py-2 text-sm"">
                @for (var i = 1; i <= 20; i++)
                {
                    <li class=""rounded-md px-2 py-1 hover:bg-accent/40"">Item @i</li>
                }
            </ul>
        </div>
    </ChildContent>
</Popover>

@code {
    private bool _open;

    private void TogglePopover()
    {
        _open = !_open;
    }
}";

    }
}
